# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_MT7601U)	+= mt7601u/
# according to mediatek, this in-kernel driver is not maintained,
# they would like to use out-of-tree mt76 driver by default.
#obj-$(CONFIG_MT76_CORE)	+= mt76/
