#mtk-camisp-drivers
PLATFORM=${PLATFORM:-@GENIO_PLATFORM@}
PACKAGE_NAME="mediatek-camisp-${PLATFORM}"
PACKAGE_VERSION="24.1"

MAKE="'make' PLATFORM=$PLATFORM KERNEL_SRC=$kernel_source_dir"
CLEAN="'make' PLATFORM=$PLATFORM KERNEL_SRC=$kernel_source_dir clean"


# drivers/media/platform/mtk-camera/mtk_camera.ko
# drivers/media/platform/mtk-isp/isp_7x/camsys/src/mtk-cam-isp.ko
# drivers/media/platform/mtk-isp/isp_7x/camsys/src/mtk-cam-plat-impl.ko
# drivers/media/platform/mtk-isp/isp_7x/camsys/src/mtk-cam-plat-util.ko
# drivers/media/platform/mtk-isp/isp_7x/imgsys/mtk_imgsys_hw_isp.ko
# drivers/media/platform/mtk-isp/isp_7x/imgsys/mtk_imgsys_util.ko
# drivers/media/platform/mtk-isp/isp_7x/mtk-hcp/mtk_hcp.ko
# drivers/media/platform/mtk-isp/isp_7x/mtk-ipesys-me/mtk-ipesys-me.ko
# drivers/misc/mediatek/imgsensor/src-v4l2/imgsensor-glue/imgsensor-glue.ko
# drivers/misc/mediatek/imgsensor/src-v4l2/imgsensor.ko
# drivers/remoteproc/mtk-ccd.ko
# drivers/rpmsg/mtk-ccd-rpmsg.ko


BUILT_MODULE_NAME[0]="mtk_camera"
BUILT_MODULE_LOCATION[0]="drivers/media/platform/mtk-camera"
DEST_MODULE_LOCATION[0]="/updates"

BUILT_MODULE_NAME[1]="mtk-cam-isp"
BUILT_MODULE_LOCATION[1]="drivers/media/platform/mtk-isp/isp_7x/camsys/src"
DEST_MODULE_LOCATION[1]="/updates"

BUILT_MODULE_NAME[2]="mtk-cam-plat-impl"
BUILT_MODULE_LOCATION[2]="drivers/media/platform/mtk-isp/isp_7x/camsys/src"
DEST_MODULE_LOCATION[2]="/updates"

BUILT_MODULE_NAME[3]="mtk-cam-plat-util"
BUILT_MODULE_LOCATION[3]="drivers/media/platform/mtk-isp/isp_7x/camsys/src"
DEST_MODULE_LOCATION[3]="/updates"

BUILT_MODULE_NAME[4]="mtk_imgsys_hw_isp"
BUILT_MODULE_LOCATION[4]="drivers/media/platform/mtk-isp/isp_7x/imgsys"
DEST_MODULE_LOCATION[4]="/updates"

BUILT_MODULE_NAME[5]="mtk_imgsys_util"
BUILT_MODULE_LOCATION[5]="drivers/media/platform/mtk-isp/isp_7x/imgsys"
DEST_MODULE_LOCATION[5]="/updates"

BUILT_MODULE_NAME[6]="mtk_hcp"
BUILT_MODULE_LOCATION[6]="drivers/media/platform/mtk-isp/isp_7x/mtk-hcp"
DEST_MODULE_LOCATION[6]="/updates"

BUILT_MODULE_NAME[7]="mtk-ipesys-me"
BUILT_MODULE_LOCATION[7]="drivers/media/platform/mtk-isp/isp_7x/mtk-ipesys-me"
DEST_MODULE_LOCATION[7]="/updates"

BUILT_MODULE_NAME[8]="imgsensor-glue"
BUILT_MODULE_LOCATION[8]="drivers/misc/mediatek/imgsensor/src-v4l2/imgsensor-glue"
DEST_MODULE_LOCATION[8]="/updates"

BUILT_MODULE_NAME[9]="imgsensor"
BUILT_MODULE_LOCATION[9]="drivers/misc/mediatek/imgsensor/src-v4l2"
DEST_MODULE_LOCATION[9]="/updates"

BUILT_MODULE_NAME[10]="mtk-ccd"
BUILT_MODULE_LOCATION[10]="drivers/remoteproc"
DEST_MODULE_LOCATION[10]="/updates"

BUILT_MODULE_NAME[11]="mtk-ccd-rpmsg"
BUILT_MODULE_LOCATION[11]="drivers/rpmsg"
DEST_MODULE_LOCATION[11]="/updates"

AUTOINSTALL="yes"
